### ISSUE TITLE
arduino - keeps falshing

### ISSUE THREAD

**Issue by mojoebita** [bjpirt/mirobot-arduino#10]
I just got my mirobot yesterday.

I built it and it works 60 % of the time I tried it.
I updated the UI and it worked fine, but it was still reasonable unstable. I kept getting this error message in the UI - something like "Can not reconnect to Mirobot "
In UI writes the "Firmware Version : unknown " - and has always done so.
I had to do something ...

So I did what you must not do - clicked the update-arduino-button. Now Arduino keeps flashing, and nothing works: -(

What should I do ?

P.S.
I do not have a USB to serial cable

Best regards
Morten

**Comment by bjpirt** [comment]
Hi,
Please could you double-check that the batteries you are using are fully charged / new? Happy to help troubleshoot getting it working over on the Google Group: 

https://groups.google.com/forum/#!forum/mirobot

Cheers,
Ben
