### ISSUE TITLE
Trouble updating arduino pro mini on mirobot

### ISSUE THREAD

**Issue by llewmihs** [bjpirt/mirobot-arduino#11]
I am having trouble controlling Mirobot. It says firmware unknown when I try to update.
![picture1](https://cloud.githubusercontent.com/assets/10365838/5592890/749c8628-91e1-11e4-8a40-ae20155c00b0.png)

Anything you can help with?

Joe

**Comment by bjpirt** [comment]
Closing this issue because it was picked up in the groups
